apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "manojakscluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "manojakscluster"
    spec:
      containers:
        - name: "manojakscluster"
          image: "mnaojnewcontregistry1.azurecr.io/manojakscluster"
          ports:
          - containerPort: 80